title: BabaChess
url: https://olincollege.github.io/baba-chess/
logo: "/assets/images/knight.png"

markdown: "kramdown"

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "sunrise"

plugins:
 - jekyll-feed
 - jekyll-include-cache

# Disables RSS feed icon
atom_feed:
  hide: true

header:
  show_overlay_excerpt: false

defaults:
  - values:
      layout: single

include:
  - _pages
#   - _data
