title: BabaChess
url: https://olincollege.github.io/baba-chess/
logo: "/assets/images/knight.png"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "sunrise"

markdown: "kramdown"

plugins:
 - jekyll-feed
 - jekyll-include-cache

# Disables RSS feed icon
atom_feed:
  hide: true

header:
  show_overlay_excerpt: false

defaults:
  - values:
      layout: single

include:
  - _pages
#   - _data
